name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ego-lay-atman-bay
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened.
      placeholder: Describe what happened.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Describe what is the expected behavior (or what is expected to happen).
      placeholder: What is expected.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if any)
      description: Please provide any screenshots.
  - type: input
    id: wme-version
    attributes:
      label: Where's My Editor? version
      description: |
        What version of Where's My Editor? does this bug occur in.
        To find out the version, click on help > about.
        Latest is not a version
      placeholder: Where's My Editor? version
    validations:
      required: true
  - type: input
    id: wmwpy-version
    attributes:
      label: wmwpy version
      description: |
        What version of wmwpy does this bug occur in.
        To find out the version, click on help > about.
        Latest is not a version
      placeholder: wmwpy version
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: What OS are you using?
      description: What OS are you using? e.g. Windows 10
      placeholder: e.g. Windows 10
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Output log (if relevent)
      description: |
        Please include output log.
        The log can be found under help > open log
        The log can also be found in the logs folder which is in the same folder as the app (if it's not there, blame pyinstaller). The filenames are the date and time they were created. Choose the latest one (`.log` files are just `.txt` files).

        The only part you really need is the end (last few lines. Each line starts with a time). If the error is not at the end, just copy the lines around the error.
      render: shell
